server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # 👇 Sửa thành dòng này (thêm $uri/):
        # Nghĩa là: Tìm file -> Tìm thư mục -> Không thấy thì về index.html
        try_files $uri $uri/ /index.html;
    }
}